'use client';
import { useEffect, useRef, useState } from 'react';
import { buildPlaygroundBody, initialPlaygroundDraft, newPlaygroundQuestion, previewPlaygroundBody, type PlaygroundAnswer, type PlaygroundDraft, type PlaygroundQuestion, type PlaygroundOption } from '../../lib/notebook/playground';
import type { JevPrimitive } from '../../lib/notebook/core';

type Result = { model: string; inferenceMs: number; request: unknown; response: { answers: Record<string, PlaygroundAnswer>; usage?: { input_tokens: number; output_tokens: number } } };
const json = (value: unknown) => JSON.stringify(value, null, 2);
const pct = (value: number) => `${(value * 100).toFixed(1)}%`;

export function JevPlayground({ model, configured, disabled, onBusyChange }: { model: string; configured: boolean; disabled: boolean; onBusyChange: (running: boolean) => void }) {
  const [draft, setDraft] = useState<PlaygroundDraft>(initialPlaygroundDraft);
  const [result, setResult] = useState<Result | null>(null);
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const nextId = useRef(2), controller = useRef<AbortController | null>(null);
  useEffect(() => () => controller.current?.abort(), []);
  let request: ReturnType<typeof buildPlaygroundBody> | null = null, validation = '';
  try { request = buildPlaygroundBody(draft, model); } catch (cause) { validation = cause instanceof Error ? cause.message : 'Complete the request.'; }
  const preview = request ?? previewPlaygroundBody(draft, model);
  const locked = busy || disabled;
  function update(next: (previous: PlaygroundDraft) => PlaygroundDraft) { setDraft(next); setResult(null); setError(''); }
  function changeQuestion(index: number, change: (question: PlaygroundQuestion) => PlaygroundQuestion) {
    update(previous => ({ ...previous, questions: previous.questions.map((question, position) => position === index ? change(question) : question) }));
  }
  function addQuestion(type: JevPrimitive) {
    update(previous => ({ ...previous, questions: [...previous.questions, newPlaygroundQuestion(type, nextId.current++)] }));
  }
  async function run() {
    if (locked || !configured || !request) return;
    const abort = new AbortController(); controller.current = abort; setBusy(true); onBusyChange(true); setError(''); setResult(null);
    try {
      const response = await fetch('/api/notebook', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ mode: 'playground', engine: 'jev', draft }), signal: abort.signal });
      const data = await response.json() as Result & { error?: string };
      if (!response.ok) throw new Error(data.error || 'JEV playground request failed.');
      if (!abort.signal.aborted) setResult(data);
    } catch (cause) { if (!abort.signal.aborted) setError(cause instanceof Error ? cause.message : 'JEV playground request failed.'); }
    finally { controller.current = null; setBusy(false); onBusyChange(false); }
  }
  return <section id="jev-playground" className="panel notebook-cell playground-cell"><span className="cell-number">[2] BUILD YOUR OWN REQUEST</span><h2>Start with any statement</h2>
    <p>Describe a support message, product, applicant, situation, or anything you want Jev to judge. Add one or more narrow questions. The TypeSafe JSON below updates as you type; Run sends all valid questions in one call.</p>
    <label>State / statement<textarea aria-label="Playground statement" rows={4} maxLength={5000} value={draft.state} disabled={locked} onChange={event => update(previous => ({ ...previous, state: event.target.value }))}/></label>
    <div className="playground-toolbar"><span>Questions · {draft.questions.length}/8</span><button disabled={locked || draft.questions.length >= 8} onClick={() => addQuestion('choice')}>+ Choice</button><button disabled={locked || draft.questions.length >= 8} onClick={() => addQuestion('score')}>+ Score</button><button disabled={locked || draft.questions.length >= 8} onClick={() => addQuestion('noul')}>+ Noul</button></div>
    <div className="playground-questions">{draft.questions.map((question, index) => <article key={index} className="playground-question"><div className="playground-question-head"><strong>Question {index + 1}</strong><button disabled={locked} onClick={() => update(previous => ({ ...previous, questions: previous.questions.filter((_, position) => position !== index) }))} aria-label={`Remove question ${question.id}`}>Remove</button></div><div className="playground-fields"><label>Question ID<input aria-label={`Question ${index + 1} ID`} maxLength={40} value={question.id} disabled={locked} onChange={event => changeQuestion(index, current => ({ ...current, id: event.target.value }))}/></label><label>Primitive<select aria-label={`Question ${index + 1} primitive`} value={question.type} disabled={locked} onChange={event => changeQuestion(index, current => ({ ...current, type: event.target.value as JevPrimitive }))}><option value="choice">Choice · select one option</option><option value="score">Score · ordered levels</option><option value="noul">Noul · yes or no</option></select></label></div><label>Instructions<textarea aria-label={`Question ${index + 1} instructions`} rows={2} maxLength={500} value={question.instructions} disabled={locked} onChange={event => changeQuestion(index, current => ({ ...current, instructions: event.target.value }))}/></label>
      {question.type === 'choice' && <div className="playground-criteria"><h3>Choice criteria · option label and meaning</h3>{question.options.map((option, optionIndex) => <div className="playground-option" key={optionIndex}><label>Label<input aria-label={`Question ${index + 1} option ${optionIndex + 1} label`} maxLength={40} value={option.key} disabled={locked} onChange={event => changeQuestion(index, current => ({ ...current, options: current.options.map((item, position) => position === optionIndex ? { ...item, key: event.target.value } : item) }))}/></label><label>Description<input aria-label={`Question ${index + 1} option ${optionIndex + 1} description`} maxLength={300} value={option.description} disabled={locked} onChange={event => changeQuestion(index, current => ({ ...current, options: current.options.map((item, position) => position === optionIndex ? { ...item, description: event.target.value } : item) }))}/></label><button disabled={locked || question.options.length <= 2} onClick={() => changeQuestion(index, current => ({ ...current, options: current.options.filter((_, position) => position !== optionIndex) }))} aria-label={`Remove option ${optionIndex + 1}`}>×</button></div>)}<button disabled={locked || question.options.length >= 20} onClick={() => changeQuestion(index, current => { let number = current.options.length + 1; while (current.options.some((option: PlaygroundOption) => option.key === `option_${number}`)) number++; return { ...current, options: [...current.options, { key: `option_${number}`, description: '' }] }; })}>+ Add option</button></div>}
      {question.type === 'score' && <div className="playground-criteria"><h3>Score criteria · ordered levels, low to high</h3>{question.levels.map((level, levelIndex) => <div className="playground-option playground-level" key={levelIndex}><span>{levelIndex}</span><label>Level {levelIndex}<input aria-label={`Question ${index + 1} level ${levelIndex}`} maxLength={300} value={level} disabled={locked} onChange={event => changeQuestion(index, current => ({ ...current, levels: current.levels.map((item, position) => position === levelIndex ? event.target.value : item) }))}/></label><button disabled={locked || question.levels.length <= 2} onClick={() => changeQuestion(index, current => ({ ...current, levels: current.levels.filter((_, position) => position !== levelIndex) }))} aria-label={`Remove level ${levelIndex}`}>×</button></div>)}<button disabled={locked || question.levels.length >= 10} onClick={() => changeQuestion(index, current => ({ ...current, levels: [...current.levels, ''] }))}>+ Add level</button></div>}
      {question.type === 'noul' && <div className="playground-criteria"><h3>Noul criteria · optional, fill both or leave both empty</h3><div className="playground-fields"><label>Yes / true<input aria-label={`Question ${index + 1} true criteria`} maxLength={300} value={question.trueDescription} disabled={locked} onChange={event => changeQuestion(index, current => ({ ...current, trueDescription: event.target.value }))}/></label><label>No / false<input aria-label={`Question ${index + 1} false criteria`} maxLength={300} value={question.falseDescription} disabled={locked} onChange={event => changeQuestion(index, current => ({ ...current, falseDescription: event.target.value }))}/></label></div></div>}
    </article>)}</div>
    <div className="notebook-code-pair"><div><h3>Live TypeSafe request JSON</h3><pre aria-label="Live JEV request JSON">{json(preview)}</pre>{validation && <p className="playground-validation" role="status">Complete the request: {validation}</p>}</div><div><h3>Live result</h3>{result ? <><p><strong>{result.model}</strong> · {(result.inferenceMs / 1000).toFixed(2)} s provider round trip{result.response.usage ? ` · ${result.response.usage.input_tokens} input / ${result.response.usage.output_tokens} output tokens` : ''}</p>{Object.entries(result.response.answers).map(([id, answer]) => <div className="playground-answer" key={id}><b>{id}</b><span>{answer.type === 'choice' ? `Choice: ${answer.choice}` : answer.type === 'score' ? `Score: ${answer.score}` : `Yes probability: ${pct(answer.noul!)}`}{answer.confidence !== undefined ? ` · confidence ${pct(answer.confidence)}` : ''}</span>{answer.probabilities && Object.entries(answer.probabilities).map(([option, probability]) => <div className="playground-probability" key={option}><small>{option}</small><progress max={1} value={probability}/><small>{pct(probability)}</small></div>)}</div>)}<details><summary>Validated response JSON</summary><pre>{json(result.response)}</pre></details><details><summary>Exact request sent</summary><pre>{json(result.request)}</pre></details></> : <p>Run a valid request to see Jev’s actual answers and probabilities. Results are cleared when you edit the request.</p>}</div></div>
    <div className="playground-actions"><button className="primary" disabled={locked || !configured || !request} onClick={run}>{busy ? 'Calling JEV…' : 'Run custom JEV request'}</button>{busy && <button onClick={() => controller.current?.abort()}>Stop</button>}<span>{configured ? `Model: ${model}` : 'Set JEV_API_KEY to enable Run.'}</span></div>{error && <p className="error" role="alert">{error}</p>}
    <p>Choice needs named options; Score needs 2–10 ordered levels; Noul asks one yes/no question and may omit criteria. <a href="https://docs.typesafe.ai/primitives/choice" target="_blank" rel="noreferrer">Choice</a> · <a href="https://docs.typesafe.ai/primitives/score" target="_blank" rel="noreferrer">Score</a> · <a href="https://docs.typesafe.ai/primitives/noul" target="_blank" rel="noreferrer">Noul</a>.</p>
  </section>;
}
